[package]
name = "async_rustbus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
async-std = "1.9.0"
async-rustbus = "0.1.1"
