[package]
name = "dbus_bytestream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
dbus-bytestream = "0.1.4"
dbus-serialize = "0.1.2"
