[package]
name = "zvariant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
serde = "1.0.0"
zvariant = "2.7.0"
zvariant_derive = "2.7.0"
zbus = "1.9.1"
